"use client"; // Add this to make it a client-side component

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNavbar from "./components/top-nav/page";
import BottomNav from "./components/bottom-nav/page";
import { usePathname } from 'next/navigation';


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  let backgroundClass = '';

  if (pathname === '/') {
    backgroundClass = 'bg-gradient';
  } else if (pathname === '/our-teams') {
    backgroundClass = 'bg-teams';
  }
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Archivo:ital,wght@0,100..900;1,100..900&family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
      </head>
      <body className={`relative ${backgroundClass}`}>
        <div className="fixed w-screen">
          <TopNavbar />
        </div>
        
        <div className="z-0 overflow-x-hidden">
          {children}
        </div>
        <BottomNav />
      </body>
    </html>
  );

}
